name: Runners in Runner with nested-github-runners-action

on:
  workflow_dispatch:

jobs:
  create-runners:
    runs-on: self-hosted
    steps:
    - name: Run Multiple GitHub Runners in Runner
      uses: dougcalobrisi/nested-github-runners-action@v0.9
      with:
        runners: 3
        github-token: ${{ secrets.GH_TOKEN }}
        shared-volume: /home/ec2-user/nested-gihtub-runner/shared
        shared-volume-host-path: /home/ec2-user/nested-gihtub-runner/shared

  runner1:
    runs-on: nested-${{ github.run_id }}
    steps:
    - name: echo hostname
      run: |
        echo `hostname`

  runner2:
    runs-on: nested-${{ github.run_id }}
    steps:
    - name: echo hostname
      run: |
        echo `hostname`

  runner3:
    runs-on: nested-${{ github.run_id }}
    steps:
    - name: echo hostname
      run: |
        echo `hostname`
